version: "3"

services:
  main:
    container_name: bot
    build: 
      context: ./
      dockerfile: prod.Dockerfile
    networks:
      - annoybot-network
    env_file:
      - .env
      - .env.local
    volumes:
      - ./src:/app/src
    restart: always
    depends_on:
      - redis
  redis:
    container_name: redis
    build: 
      dockerfile: redis.Dockerfile
    networks:
      - annoybot-network
    restart: always
    ports:
      - 6379:6379

networks:
  annoybot-network:
    name: annoybot-network
    driver: bridge

