import discord
from discord.ext import commands
from discord import app_commands
import random
import asyncio
from typing import Optional
import re


class Roletroll(commands.Cog):
    """Give a target a nasty coloured role with an insulting name"""

    def __init__(self, bot):
        self.bot = bot
        self.ugly_colors = ("4a412a", "93934a", "32cd32", "654321")

    @app_commands.command(
        name="roletroll",
        description="Give a target a nasty coloured role with an insulting name",
    )
    @app_commands.guild_only()
    @app_commands.describe(
        user="Who to give to role to",
        name="The name of the role",
        colour="The colour of the role. If left empty, a random shit colour will be given",
    )
    @app_commands.checks.bot_has_permissions(manage_roles=True)
    async def color(
        self,
        interaction: discord.Interaction,
        user: discord.Member,
        name: str,
        colour: Optional[app_commands.Range[str, 6, 6]] = None,
    ):
        if colour is not None and not re.search(
            "^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$", colour
        ):
            await interaction.response.send_message(
                "❌ Enter a valid hex code, idiot.", ephemeral=True
            )
            return
        elif colour is None:
            colour = random.choice(self.ugly_colors)
        role = await interaction.guild.create_role(
            name=name, color=int(colour, 16), hoist=True
        )
        await user.add_roles(role)
        await interaction.response.send_message(
            f"Given temporary role with name ``{name}`` to {user.display_name}"
        )
        await asyncio.sleep(30)
        await role.delete(reason="Automatic removal of role generated by /roletroll")


async def setup(bot):
    await bot.add_cog(Roletroll(bot))
